notifications:
  punishment:
    # The url of Discord Webhook. Set this value to empty to disable notifications.
    webhook-url: ""
    # The id of the thread. If you are using forum channel, you need to set this id.
    thread-id: 0
  alt:
    # The url of Discord Webhook. Set this value to empty to disable notifications.
    webhook-url: ""
    # The id of the thread. If you are using forum channel, you need to set this id.
    thread-id: 0
    # If set to true, only banned alts will be notified.
    only-banned-alt: false
    # If set to true, only same IP alts will be notified.
    only-strong-possibility: true
